# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or:
          - css
          - html
          - javascript
          - yaml
          - json
        additional_dependencies:
          - prettier@2.5.1

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0-alpha.1
    hooks:
      - id: eslint
        args:
          - --fix
        additional_dependencies:
          - eslint@8.6.0
          - eslint-config-google@0.14.0
          - eslint-config-prettier@8.3.0
